INSERT INTO sectors (id, name, parent_id, level, sort_order) VALUES
(1,   'Manufacturing',                                    NULL, 0,  1),
(19,  'Construction materials',                           1,    1,  2),
(18,  'Electronics and Optics',                           1,    1,  3),
(6,   'Food and Beverage',                                1,    1,  4),
(342, 'Bakery & confectionery products',                  6,    2,  5),
(43,  'Beverages',                                        6,    2,  6),
(42,  'Fish & fish products',                             6,    2,  7),
(40,  'Meat & meat products',                             6,    2,  8),
(39,  'Milk & dairy products',                            6,    2,  9),
(437, 'Other',                                            6,    2,  10),
(378, 'Sweets & snack food',                              6,    2,  11),
(13,  'Furniture',                                        1,    1,  12),
(389, 'Bathroom/sauna',                                   13,   2,  13),
(385, 'Bedroom',                                          13,   2,  14),
(390, 'Children''s room',                                 13,   2,  15),
(98,  'Kitchen',                                          13,   2,  16),
(101, 'Living room',                                      13,   2,  17),
(392, 'Office',                                           13,   2,  18),
(394, 'Other (Furniture)',                                13,   2,  19),
(341, 'Outdoor',                                          13,   2,  20),
(99,  'Project furniture',                                13,   2,  21),
(12,  'Machinery',                                        1,    1,  22),
(94,  'Machinery components',                             12,   2,  23),
(91,  'Machinery equipment/tools',                        12,   2,  24),
(224, 'Manufacture of machinery',                         12,   2,  25),
(97,  'Maritime',                                         12,   2,  26),
(271, 'Aluminium and steel workboats',                    97,   3,  27),
(269, 'Boat/Yacht building',                              97,   3,  28),
(230, 'Ship repair and conversion',                       97,   3,  29),
(93,  'Metal structures',                                 12,   2,  30),
(508, 'Other',                                            12,   2,  31),
(227, 'Repair and maintenance service',                   12,   2,  32),
(11,  'Metalworking',                                     1,    1,  33),
(67,  'Construction of metal structures',                 11,   2,  34),
(263, 'Houses and buildings',                             11,   2,  35),
(267, 'Metal products',                                   11,   2,  36),
(542, 'Metal works',                                      11,   2,  37),
(75,  'CNC-machining',                                    542,  3,  38),
(62,  'Forgings, Fasteners',                              542,  3,  39),
(69,  'Gas, Plasma, Laser cutting',                       542,  3,  40),
(66,  'MIG, TIG, Aluminum welding',                       542,  3,  41),
(9,   'Plastic and Rubber',                               1,    1,  42),
(54,  'Packaging',                                        9,    2,  43),
(556, 'Plastic goods',                                    9,    2,  44),
(559, 'Plastic processing technology',                    9,    2,  45),
(55,  'Blowing',                                          559,  3,  46),
(57,  'Moulding',                                         559,  3,  47),
(53,  'Plastics welding and processing',                  559,  3,  48),
(560, 'Plastic profiles',                                 9,    2,  49),
(5,   'Printing',                                         1,    1,  50),
(148, 'Advertising',                                      5,    2,  51),
(150, 'Book/Periodicals printing',                        5,    2,  52),
(145, 'Labelling and packaging printing',                 5,    2,  53),
(7,   'Textile and Clothing',                             1,    1,  54),
(44,  'Clothing',                                         7,    2,  55),
(45,  'Textile',                                          7,    2,  56),
(8,   'Wood',                                             1,    1,  57),
(337, 'Other (Wood)',                                     8,    2,  58),
(51,  'Wooden building materials',                        8,    2,  59),
(47,  'Wooden houses',                                    8,    2,  60),
(3,   'Other',                                            NULL, 0,  61),
(37,  'Creative industries',                              3,    1,  62),
(29,  'Energy technology',                                3,    1,  63),
(33,  'Environment',                                      3,    1,  64),
(2,   'Service',                                          NULL, 0,  65),
(25,  'Business services',                                2,    1,  66),
(35,  'Engineering',                                      2,    1,  67),
(28,  'Information Technology and Telecommunications',    2,    1,  68),
(581, 'Data processing, Web portals, E-marketing',        28,   2,  69),
(576, 'Programming, Consultancy',                         28,   2,  70),
(121, 'Software, Hardware',                               28,   2,  71),
(122, 'Telecommunications',                               28,   2,  72),
(22,  'Tourism',                                          2,    1,  73),
(141, 'Translation services',                             2,    1,  74),
(21,  'Transport and Logistics',                          2,    1,  75),
(111, 'Air',                                              21,   2,  76),
(114, 'Rail',                                             21,   2,  77),
(112, 'Road',                                             21,   2,  78),
(113, 'Water',                                            21,   2,  79);
